# SERVER SETTING in local or prod file

spring:
  application:
    name: auth-service

  profiles:
    include: redis


#LOGIN SETTING
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${OAUTH_LOGIN_URL}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${OAUTH_LOGIN_URL}/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jwt:
    secret: ${JWT_SECRET}

#MVC : HELPING FIND PATH LIKE /** OR /*
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#REDIS setting in local or prod file
## SERIALIZATION ERROR CONTROLLER FOR REDIS
  jackson:
    serialization:
      fail-on-empty-beans: false

#JPA
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


#Swagger settings : DOCS PATH SETTING
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true



#Actuator settings : FOR DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

front:
  url: ${FRONT_URL}
