spring:
  application:
    name: chat-service
  config:
    import: classpath:prompt.yml  # 기존 spring.config.import=classpath:prompt.yml
  cloud:
    openfeign:
      client:
        config:
          auth-service:
            url: http://localhost:8081 #auth
server:
  port: 8084

# Eureka 설정
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

# Swagger 관련 설정
swagger:
  gateway:
    url: ${GATEWAY_SERVICE_URL}
  chat:
    url: ${CHAT_SERVICE_URL}

livekit:
  api:
    key: ${LIVEKIT_API_KEY}
    secret: ${LIVEKIT_API_SECRET}
  url: ${LIVEKIT_URL}

mongo:
  initdb:
    uri: ${MONGO_INITDB_URI}
    database: ${MONGO_INITDB_DATABASE}

auth:
  service:
    url: ${AUTH_SERVICE_URL}

comment:
  service:
    url: ${COMMENT_SERVICE_URL}

openai:
  api:
    key: ${OPENAI_API_KEY}

# Actuator 설정 (Spring Boot 3.4.1 기준)
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"  # 필요한 엔드포인트들을 쉼표로 구분하여 문자열로 지정합니다.
  endpoint:
    health:
      show-components: always         # 헬스 체크 시 상세 정보를 항상 노출합니다.