
#Server Setting
server:
  port: 8080

#FOR TOEKN
jwt:
  secret: ${JWT_SECRET}

# Spring WebFlux - WebApplication environement setting
spring:
  main:
    web-application-type: reactive


  #Application name
  application:
    name: Gateway

#Setting profile
  profiles:
    include:


#Gateway Setting
  cloud:
    gateway:
      forwarded:
        enabled: false
        # 기존 헤더를 유지하지 않고 덮어쓰기
        append: false
      httpclient:
        connect-timeout: 2000 #try connecting for 2sec
        response-timeout: 60s #wating max 10sec until getting response from server
      # route setting
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/oauth/**
        - id: support-service
          uri: lb://SUPPORT-SERVICE
          predicates:
            - Path=/api/support/**
        - id: match-service
          uri: lb://MATCH-SERVICE
          predicates:
            - Path=/api/match/**
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/chat/**

# Eureka Setting
eureka:
  client:
    register-with-eureka: false #REGISTER IN EUREKA T/F, Dont need to be regist
    fetch-registry: true #GET OTHER SERVICE FROM EUREKA AND COMMUNICATE
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}/eureka/ #EUREKA SERVER URL
  instance:
    prefer-ip-address: true # FALSE : REGIST SERVICE BY HOSTNAME EX) LOCALHOST(might cause error in docker) / TRUE : REGIST SERVICE BY IP
    leaseRenewalIntervalInSeconds: 5 #GATEWAY CONNECT TO EUREKA SERVER PER 5SEC, REFRESH SERVICE INSTANCE
    leaseExpirationDurationInSeconds: 10 #EUREKA DELETE SERVICE INSTANCE IF DOES NOT REFRESH UNTIL 10 SEC
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #MAKE Instance unique ID

#Swagger setting
springdoc:
  swagger-ui:
    urls:
      - name: auth service
        url: ${AUTH_SERVICE_URL}/v3/api-docs
      - name: support service
        url: ${SUPPORT_SERVICE_URL}/v3/api-docs
      - name: chat service
        url: ${CHAT_SERVICE_URL}/v3/api-docs
      - name: match service
        url: ${MATCH_SERVICE_URL}/v3/api-docs

# urls
front:
  url: ${FRONT_URL}

gateway:
  service:
    url: ${GATEWAY_SERVICE_URL}