spring:
  application:
    name: match-service
  cloud:
    openfeign:
      client:
        config:
          auth-service:
            connectTimeout: 5000  # 최소한 하나의 설정이 필요
            readTimeout: 5000
          chat-service:
            connectTimeout: 5000  # 최소한 하나의 설정이 필요
            readTimeout: 5000


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true

# External API url
ai:
  service:
    url: ${AI_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-components: always