spring:
  application:
    name: match-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Swagger URL은 환경변수(GATEWAY_SERVICE_URL, MATCH_SERVICE_URL)를 통해 주입받습니다.
swagger:
  gateway:
    url: ${GATEWAY_SERVICE_URL}
  match:
    url: ${MATCH_SERVICE_URL}