spring:
  application:
    name: Match

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Swagger URL 설정(기본값 또는 환경 변수를 통해 주입 가능)
swagger:
  gateway:
    url: ${GATEWAY_SERVICE_URL}
  match:
    url: ${MATCH_SERVICE_URL}