spring:
    data:
        redis:
            port: 6379
            host: localhost
            password: ${REDIS_PASSWORD}

server:
    address: localhost
    port: 8083

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            # 로컬에서는 환경변수(EUREKA_SERVICE_URL)가 없을 경우 기본값 http://localhost:8671 사용
            defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8671}/eureka/
    instance:
        prefer-ip-address: true
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 10
        ip-address: 127.0.0.1
        instance-id: ${spring.application.name}:${server.port}

swagger:
    gateway:
        # 기본값: 로컬 게이트웨이 URL
        url: ${GATEWAY_SERVICE_URL:http://localhost:8080}
    match:
        # 기본값: 로컬 매치 서비스 URL
        url: ${MATCH_SERVICE_URL:http://localhost:8083}