spring:
  data:
    redis:
      port: 6379
      host: localhost
      password: ${REDIS_PASSWORD}

server:
  address: localhost
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

