spring:
  application:
    name: Match
  config:
    import: optional:classpath:/application-secret.yml
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8083

ai:
  service:
    url: localhost:8085

chat:
  service:
    url: localhost:8084

auth:
  service:
    url: localhost:8081