spring:
  application:
    name: Match

server:
  url: ${MATCH_SERVICE_URL}
  port: 8083

gateway:
  service:
    url: ${GATEWAY_SERVICE_URL}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html